name: dbt_project
version: "1.0.0"
config-version: 2

profile: dbt_project

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    final:
      +materialized: table
